# Generated by Django 3.2.4 on 2021-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
