# Generated by Django 3.2.4 on 2021-07-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping', '0005_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
