# Generated by Django 3.2.4 on 2021-07-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping', '0011_auto_20210724_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Shoping.Category', verbose_name='دسته بندی ها'),
        ),
    ]
