# Generated by Django 3.2.4 on 2021-07-25 07:08

import Shoping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping', '0012_auto_20210724_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=Shoping.models.upload_image_path, verbose_name='تصویر')),
            ],
        ),
    ]
