# Generated by Django 3.2.4 on 2021-07-25 13:19

import Shoping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping', '0014_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=Shoping.models.upload_image_Gallery_path, verbose_name='تصویر'),
        ),
    ]
