# Generated by Django 3.2.4 on 2021-07-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping', '0015_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=150, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(verbose_name='خوانده شده / نشده')),
            ],
        ),
    ]
