# Generated by Django 3.2.5 on 2021-07-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping', '0020_rename_owner_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='owner',
        ),
    ]
